
build:
  tags:
    - maven
    - docker
  script:
    - mvn clean compile

test:
  tags:
    - maven
    - docker
  script:
    - mvn -B -P ci org.jacoco:jacoco-maven-plugin:prepare-agent verify -Dmaven.test.failure.ignore=true
    - mvn -B sonar:sonar -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME

deploy:
  tags:
    - maven
    - docker
  script:
    - mvn -B install site:site
